package com.swengle.phoebe.test.model;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;

public class EntityWithAutoGeneratedHashKeyAndAutoGeneratedRangeKey extends EntityWithAutoGeneratedHashKeyAndRangeKey  {
	/**
	 * @return the rangeId
	 */
	@DynamoDBRangeKey(attributeName="rangeKey")
	@DynamoDBAutoGeneratedKey
	public String getRangeKey() {
		return super.getRangeKey();
	}
}
