package com.swengle.phoebe.test.model;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;

public class EntityWithAutoGeneratedHashKey extends EntityWithHashKey {
	@DynamoDBHashKey(attributeName="hashKey")
	@DynamoDBAutoGeneratedKey
	public String getHashKey() {
		return super.getHashKey();
	}
}
