package com.swengle.phoebe.test.model;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;

public class ObjectWithAutoGeneratedHashKey extends ObjectWithHashKey {
	@DynamoDBHashKey(attributeName="id1")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return super.getId();
	}
}
