package com.swengle.phoebe.test.model;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;

public class ObjectWithHashKeyAndAutoGeneratedRangeKey extends ObjectWithHashKeyAndRangeKey {
	/**
	 * @return the rangeId
	 */
	@DynamoDBRangeKey(attributeName="id2")
	@DynamoDBAutoGeneratedKey
	public String getRangeId() {
		return super.getRangeId();
	}
}
